### ISSUE TITLE
Small correction

### ISSUE THREAD

**Issue by votality** [VolgemutNik/rfc3161-timestamping#1]
Firstly thanks so much for the example, cleared up how to use the c# rfc3161 timestamp library. I had to make a small change to get it to work. "hashBytes" when calling timestampToken.VerifySignatureForHash should be "hash".

**Comment by t0xk** [comment]
Thanks for pointing out my mistake. I did not properly refactor that part of the code when transfering it out of another project. Should now be resolved.
